version: 0.2

phases:
  pre_build:
    commands:
      - echo "Login en ECR..."
      - aws ecr get-login-password | docker login --username AWS --password-stdin 884178094984.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Construyendo imagen del backend..."
      - docker build -t backend-app ./backend
      - docker tag backend-app:latest 884178094984.dkr.ecr.us-east-1.amazonaws.com/backend-app:latest
  post_build:
    commands:
      - echo "Subiendo imagen a ECR..."
      - docker push 884178094984.dkr.ecr.us-east-1.amazonaws.com/backend-app:latest