version: 0.2

phases:
  pre_build:
    commands:
      - echo "Iniciando fase pre_build..."
      - echo "Login en Amazon ECR..."
      - aws ecr get-login-password | docker login --username AWS --password-stdin 884178094984.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=884178094984.dkr.ecr.us-east-1.amazonaws.com/backend-app
      - IMAGE_TAG=latest

  build:
    commands:
      - echo "Construyendo imagen Docker..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG ./backend

  post_build:
    commands:
      - echo "Subiendo imagen a Amazon ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Creando archivo imagedefinitions.json..."
      - printf '[{"name":"backend","imageUri":"%s"}]' "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
